### ISSUE TITLE
Need Reboot Or Restart Service After Lock

### ISSUE THREAD

**Issue by jamkar20** [elementary/greeter#557]
## What Happened
Greeter hide login box When Lock Screen Manually Or Automatically 

### Logs
Lightdm Logs:
Failed to flush data to greeter : Broken Pipe
../../glib/giounix.c:410 while getting flags for FD : Bad File Descriptor
Invalid File Descriptor

## Platform Information
Elementary OS 6
Lenovo Y700
i7-6700hq
24 gb ram
256 ssd
nvidia 960m / intel 530

**Comment by zhrexl** [comment]
The same happened to me. I needed to lock my computer for 5 minutes and when i couldnt see the box to unlock the system.
Ended up losing my work :/
I didn't receive the same logs and perhaps I should open a new issue?
This is what I can provide:
Journalctl logs: 

> set 23 15:34:38 DougNote gala.desktop[1308]: Window manager warning: Window 0x3600001 has property _NET_WM_PID
> set 23 15:34:38 DougNote gala.desktop[1308]: that was expected to have type CARDINAL format 32
> set 23 15:34:38 DougNote gala.desktop[1308]: and actually has type ATOM format 32 n_items 0.
> set 23 15:34:38 DougNote gala.desktop[1308]: This is most likely an application bug, not a window manager bug.
> set 23 15:34:38 DougNote gala.desktop[1308]: The window has title="unknown" class="unknown" name="unknown"
> set 23 15:34:42 DougNote MATLAB[4012]: Failed to load module "canberra-gtk-module"
> set 23 15:34:43 DougNote gala.desktop[1308]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x380002f specified for 0x3800047.
> set 23 15:34:44 DougNote gala[1308]: Error in map accounting.
> set 23 15:34:46 DougNote gala[1308]: clutter_actor_add_effect_with_name: assertion 'CLUTTER_IS_ACTOR (self)' failed
> set 23 15:34:46 DougNote gala[1308]: clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (child)' failed
> set 23 15:34:46 DougNote gala[1308]: invalid (NULL) pointer instance
> set 23 15:34:46 DougNote gala[1308]: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> set 23 15:43:51 DougNote gala[1308]: clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (child)' failed
> set 23 15:43:51 DougNote gala[1308]: invalid (NULL) pointer instance
> set 23 15:43:51 DougNote gala[1308]: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> set 23 15:43:51 DougNote gala[1308]: clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (child)' failed
> set 23 15:43:51 DougNote gala[1308]: invalid (NULL) pointer instance
> set 23 15:43:51 DougNote gala[1308]: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> set 23 15:43:51 DougNote gala[1308]: clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (child)' failed
> set 23 15:43:51 DougNote gala[1308]: invalid (NULL) pointer instance
> set 23 15:43:51 DougNote gala[1308]: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> set 23 15:43:51 DougNote gala[1308]: clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (child)' failed
> set 23 15:43:51 DougNote gala[1308]: invalid (NULL) pointer instance
> set 23 15:43:51 DougNote gala[1308]: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> set 23 15:51:46 DougNote gala[1308]: clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (child)' failed
> set 23 15:51:46 DougNote gala[1308]: invalid (NULL) pointer instance
> set 23 15:51:46 DougNote gala[1308]: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> set 23 15:51:46 DougNote gala[1308]: clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (child)' failed
> set 23 15:51:46 DougNote gala[1308]: invalid (NULL) pointer instance
> set 23 15:51:46 DougNote gala[1308]: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> set 23 15:51:46 DougNote gala[1308]: clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (child)' failed
> set 23 15:51:46 DougNote gala[1308]: invalid (NULL) pointer instance
> set 23 15:51:46 DougNote gala[1308]: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> set 23 15:51:46 DougNote gala[1308]: clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (child)' failed
> set 23 15:51:46 DougNote gala[1308]: invalid (NULL) pointer instance
> set 23 15:51:46 DougNote gala[1308]: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> set 23 16:07:38 DougNote io.elementary.s[4937]: gee_abstract_collection_get_size: assertion 'self != NULL' failed
> set 23 16:07:38 DougNote io.elementary.s[4937]: gee_abstract_collection_add: assertion 'self != NULL' failed
> set 23 16:07:39 DougNote gala[1308]: clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (child)' failed
> set 23 16:07:39 DougNote gala[1308]: invalid (NULL) pointer instance
> set 23 16:07:39 DougNote gala[1308]: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> set 23 16:07:45 DougNote gsd-color[1222]: failed to set screen _ICC_PROFILE: Falha ao abrir arquivo “/var/lib/lightdm/.local/share/icc/edid-298c87494c7c3e7e9d86bc850b066031.icc”: Permissão negada
> set 23 16:08:35 DougNote gsd-color[1222]: failed to set screen _ICC_PROFILE: Falha ao abrir arquivo “/var/lib/lightdm/.local/share/icc/edid-298c87494c7c3e7e9d86bc850b066031.icc”: Permissão negada
> set 23 16:16:20 DougNote gsd-power[1204]: Failed to acquire idle monitor proxy: O tempo limite foi alcançado
> set 23 16:24:10 DougNote gnome-keyring-daemon[1056]: asked to register item /org/freedesktop/secrets/collection/login/2, but it's already registered
> set 23 17:14:49 DougNote gsd-color[1222]: failed to set screen _ICC_PROFILE: Falha ao abrir arquivo “/var/lib/lightdm/.local/share/icc/edid-298c87494c7c3e7e9d86bc850b066031.icc”: Permissão negada
> set 23 17:15:14 DougNote gsd-power[1204]: Error setting property 'PowerSaveMode' on interface org.gnome.Mutter.DisplayConfig: O tempo limite foi alcançado (g-io-error-quark, 24)


Here's Matlab (was open when it happened) logs: 

>   Operating System: Linux 5.11.0-36-generic #40~20.04.1-Ubuntu SMP Sat Sep 18 02:14:19 UTC 2021 x86_64
  Processor ID:     x86 Family 6 Model 142 Stepping 12, GenuineIntel
  Host Name:        DougNote
FATAL ERROR in native method: Nativewindow X11 IOError: Display 0x7f94790bb390 (:0): Recurso temporariamente indisponível
FATAL ERROR in native method: Nativewindow X11 IOError: Display 0x7f951435d570 (:0): Recurso temporariamente indisponível
	at sun.awt.X11.XlibWrapper.XSync(Native Method)
	at sun.awt.X11.XToolkit.XSync(XToolkit.java:1271)
	at sun.awt.X11.XWM.unshadeKludge(XWM.java:1286)
	at sun.awt.X11.XDecoratedPeer.handleReparentNotifyEvent(XDecoratedPeer.java:337)
	at sun.awt.X11.XBaseWindow.dispatchEvent(XBaseWindow.java:1140)
	at sun.awt.X11.XBaseWindow.dispatchToWindow(XBaseWindow.java:1086)
	at sun.awt.X11.XToolkit.dispatchEvent(XToolkit.java:502)
	at sun.awt.X11.XToolkit.run(XToolkit.java:616)
	at sun.awt.X11.XToolkit.run(XToolkit.java:532)
	at java.lang.Thread.run(Thread.java:748)


**System**: Elementary OS 6 Odin
**Memory**: 8 Gb
**CPU**: i5 8265U
**GPU**: Intel UHD Graphics 620

**Comment by peteruithoven** [comment]
This might be the same issue as https://github.com/elementary/greeter/issues/411
